<?php

namespace Dview\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiteRepository extends EntityRepository {

    /**
     * Returns suites count for a specific user. Don't specify the user if he is an admin.
     * 
     * @param type $user           Suites owner
     * @return type
     */
    public function getCount($user) {
        $query = $this
                ->createQueryBuilder('s')
                ->leftJoin('s.project', 'p')
                ->leftJoin('p.manager', 'm')
                ->select('count (s)');
        if ($user != NULL) {
            $query->where('p.manager = :id')
                    ->orWhere('p.client = :id')
                    ->setParameter('id', $user->getId());
        }
        return $query->getQuery()
                        ->getSingleScalarResult();
    }

}
