<?php

namespace Dview\ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository {

    /**
     * Returns tests count for a specific user. Don't specify the user if he is an admin.
     * 
     * @param type $user           Tests owner
     * @return type
     */
    public function getCount($user) {
        $query = $this
                ->createQueryBuilder('t')
                ->leftJoin('t.suite', 's')
                ->leftJoin('s.project', 'p')
                ->leftJoin('p.manager', 'm')
                ->select('count (s)');
        if ($user != NULL) {
            $query->where('p.manager = :id')
                    ->orWhere('p.client = :id')
                    ->setParameter('id', $user->getId());
        }
        return $query->getQuery()
                        ->getSingleScalarResult();
    }

    /**
     * Returns test corresponding with given mongo id
     * 
     * @param type $idOnMongoDB
     */
    public function getTest($idOnMongoDB){
        $query = $this->createQueryBuilder('t')
                ->select('t')
                ->where('t.idOnMongoDB = :id')
                ->setParameter('id', $idOnMongoDB);
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
